ifneq (,$(wildcard ./.env))
    include .env
    export
endif

run:
	npm run build
	go run ./cmd/web/.

status:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) status

up:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) up

test_up:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_TEST_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) up

down:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) down

test_down:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_TEST_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) down

reset:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) reset

test_reset:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_TEST_DBSTRING) goose -dir=$(GOOSE_MIGRATION_DIR) reset

test_run_seeder:
	GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_TEST_DBSTRING) goose -dir=$(GOOSE_TEST_MIGRATION_DIR) -no-versioning up

create:
	goose -dir=$(GOOSE_MIGRATION_DIR) create $(file) sql
